//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:49:35 AM GMT 
//


package sharedservices.xml.travel.flights;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flighttype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flighttype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TicketClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Departure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DepartureDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestinationDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PaidFare" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Directorate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flighttype", propOrder = {
    "month",
    "ticketClass",
    "departure",
    "departureDescription",
    "destination",
    "destinationDescription",
    "paidFare",
    "supplierName",
    "directorate",
    "date"
})
public class Flighttype {

    @XmlElement(name = "Month", required = true)
    protected String month;
    @XmlElement(name = "TicketClass", required = true)
    protected String ticketClass;
    @XmlElement(name = "Departure", required = true)
    protected String departure;
    @XmlElement(name = "DepartureDescription", required = true)
    protected String departureDescription;
    @XmlElement(name = "Destination", required = true)
    protected String destination;
    @XmlElement(name = "DestinationDescription", required = true)
    protected String destinationDescription;
    @XmlElement(name = "PaidFare")
    protected int paidFare;
    @XmlElement(name = "SupplierName", required = true)
    protected String supplierName;
    @XmlElement(name = "Directorate", required = true)
    protected String directorate;
    @XmlElement(required = true)
    protected String date;

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonth(String value) {
        this.month = value;
    }

    /**
     * Gets the value of the ticketClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketClass() {
        return ticketClass;
    }

    /**
     * Sets the value of the ticketClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketClass(String value) {
        this.ticketClass = value;
    }

    /**
     * Gets the value of the departure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * Sets the value of the departure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeparture(String value) {
        this.departure = value;
    }

    /**
     * Gets the value of the departureDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureDescription() {
        return departureDescription;
    }

    /**
     * Sets the value of the departureDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureDescription(String value) {
        this.departureDescription = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the destinationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationDescription() {
        return destinationDescription;
    }

    /**
     * Sets the value of the destinationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationDescription(String value) {
        this.destinationDescription = value;
    }

    /**
     * Gets the value of the paidFare property.
     * 
     */
    public int getPaidFare() {
        return paidFare;
    }

    /**
     * Sets the value of the paidFare property.
     * 
     */
    public void setPaidFare(int value) {
        this.paidFare = value;
    }

    /**
     * Gets the value of the supplierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierName(String value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the directorate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectorate() {
        return directorate;
    }

    /**
     * Sets the value of the directorate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectorate(String value) {
        this.directorate = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

	@Override
	public String toString() {
		return "Flighttype [month=" + month + ", ticketClass=" + ticketClass + ", departure=" + departure
				+ ", departureDescription=" + departureDescription + ", destination=" + destination
				+ ", destinationDescription=" + destinationDescription + ", paidFare=" + paidFare + ", supplierName="
				+ supplierName + ", directorate=" + directorate + ", date=" + date + "]";
	}

}
